import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Provider } from "./context/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Web3Provider>

        <body className={inter.className}>
            {children}
        </body>
      
      </Web3Provider>

    </html>
  );
}
